# Generated by Django 6.0.1 on 2026-01-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
